"""Single source of truth for variant column definitions."""

VARIANT_COLUMNS: list[str] = [
    "chrom",
    "pos_range",
    "pos",
    "end_pos",
    "ref",
    "alt",
    "qual",
    "filter",
    "rs_id",
    "gene",
    "transcript",
    "hgvs_c",
    "hgvs_p",
    "consequence",
    "impact",
    "is_coding",
    "is_lof",
    "af_gnomad",
    "af_gnomad_popmax",
    "af_1kg",
    "cadd_phred",
    "clinvar_sig",
    "clinvar_review",
    "info",
    "load_batch_id",
    "sample_id",
]

VARIANT_COLUMNS_BASIC: list[str] = [
    "chrom",
    "pos_range",
    "pos",
    "end_pos",
    "ref",
    "alt",
    "qual",
    "filter",
    "rs_id",
    "gene",
    "consequence",
    "impact",
    "hgvs_c",
    "hgvs_p",
    "af_gnomad",
    "cadd_phred",
    "clinvar_sig",
    "load_batch_id",
]
